### ISSUE TITLE
Feature Request: Subtitles

### ISSUE THREAD

**Issue by kenderipa** [MicheleCioccarelli/blob-dl#5]
Hello, first of all, thanks for this great little piece of software! But could you also add the possibility to download subtitles (including language selection and automatically generated ones) and merge them into the video? Thanks!

**Comment by MicheleCioccarelli** [comment]
Subtitles are supported in the most recent build!
It will still take some time for the next release to come out but if you compile the commit titled "[[Stable build with working subtitles]]" you should be able to use this feature. (please let me know if anything is broken)

Subtitles are downloaded by default on video (or video-only) files.
 I did this because videos with official subtitles are rare and I didn't want to make the menu too complicated for something that can't be used most of the time.
Unfortunately automatically generated subtitles can't be downloaded (maybe because youtube generated the on the fly?)

If you don't want to compile blob-dl yourself you can just add `"--embed-subs"` to the yt-dlp command that you get from 

`blob-dl -s "URL"`

Thanks for making this feature request
